name = "Hexxy Test Pack"
author = "walksanator"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbee208e07ccc0bd0c96aee67c7401b49f83ed089b67a68d4a952cf602484d98"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
